"""Write the experiment run configs in configs/exp/ from one table.

Each run config is a plain, complete YAML file, so any run can be re-run from
its file alone. This script only saves typing and keeps the runs consistent.
The plan behind these runs is in EXPERIMENTS.md.

    python scripts/make_configs.py          # write the files
    python scripts/make_configs.py --check  # fail if a file is missing or out of date
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from gptlab.config import ModelConfig, config_from_dict  # noqa: E402
from gptlab.flops import estimate_param_counts  # noqa: E402

OUT = ROOT / "configs" / "exp"
TOKENS_PER_PARAM = 20  # Chinchilla's rule of thumb for compute-optimal training

# The scaling ladder. Head size is 64 everywhere. The micro-batch (sequences
# per GPU per forward pass) is what the smoke benchmark found fits on a T4.
# Smaller models get smaller batches: with few training tokens they need
# enough optimizer steps.
SIZES = {
    "s1": dict(d_model=128, n_layer=4, n_head=2, micro=32, batch=65536),
    "s2": dict(d_model=256, n_layer=6, n_head=4, micro=32, batch=65536),
    "s3": dict(d_model=384, n_layer=8, n_head=6, micro=16, batch=131072),
    "s4": dict(d_model=512, n_layer=8, n_head=8, micro=16, batch=131072),
    "s5": dict(d_model=640, n_layer=10, n_head=10, micro=16, batch=262144),
    "s6": dict(d_model=768, n_layer=12, n_head=12, micro=8, batch=262144),
}

BASE_MODEL = dict(
    pos_encoding="rope", norm="rmsnorm", norm_placement="pre",
    mlp="swiglu", tie_weights=True, qk_norm=False,
)


def lr_name(lr: float) -> str:
    """1e-3 -> "1e-3", 1.6e-2 -> "1.6e-2"."""
    mant, exp = f"{lr:.1e}".split("e")
    return f"{mant.rstrip('0').rstrip('.')}e{int(exp)}"


def model_dict(size: str, **changes) -> dict:
    s = SIZES[size]
    dims = {"d_model": s["d_model"], "n_layer": s["n_layer"], "n_head": s["n_head"]}
    return {"vocab_size": 16384, "seq_len": 1024, **dims, **BASE_MODEL, **changes}


def total_params(size: str, **model_changes) -> int:
    return estimate_param_counts(ModelConfig(**model_dict(size, **model_changes)))["total"]


def run(name: str, size: str, lr: float, notes: str, group: str, *, seed: int = 1337, data_seed: int = 1234,
        tokens_per_param: float = TOKENS_PER_PARAM, model: dict | None = None, train: dict | None = None) -> dict:
    s = SIZES[size]
    batch = (train or {}).get("global_batch_tokens", s["batch"])
    # Training length comes from the size's base model, so a variant (say GELU
    # instead of SwiGLU) trains on exactly as many tokens as the base model.
    steps = round(tokens_per_param * total_params(size) / batch)
    eval_every = max(50, 50 * round(steps / 20 / 50))  # about 20 checks per run
    cfg = {
        "name": name,
        "seed": seed,
        "notes": notes,
        "model": model_dict(size, **(model or {})),
        "data": {"name": "fineweb-edu-16k", "seed": data_seed},
        "train": {
            "tokens": steps * batch,
            "global_batch_tokens": batch,
            "micro_batch_size": s["micro"],
            "lr": lr,
            "min_lr_ratio": 0.1,
            "warmup_steps": max(10, round(0.05 * steps)),
            "schedule": "cosine",
            "weight_decay": 0.1,
            "beta1": 0.9,
            "beta2": 0.95,
            "grad_clip": 1.0,
            "z_loss": 0.0,
            "precision": "fp16",
            "compile": True,
            "debug_interval": 100,
            **(train or {}),
        },
        "eval": {"interval": eval_every, "tokens": 1048576, "final_tokens": 20971520, "hellaswag": True},
    }
    return {"group": group, "size": size, "config": cfg}


def all_runs() -> list[dict]:
    runs = []
    # Experiment A, stage 1: learning-rate sweeps on the three smallest sizes.
    # Factor-of-2 grids. The best LR per size sets the LR rule for s4-s6, and
    # the best run of each sweep is that size's point on the scaling ladder.
    sweeps = {"s1": [1e-3, 2e-3, 4e-3, 8e-3, 1.6e-2], "s2": [1e-3, 2e-3, 4e-3, 8e-3], "s3": [1e-3, 2e-3, 4e-3]}
    for size, lrs in sweeps.items():
        for lr in lrs:
            runs.append(run(f"{size}-lr{lr_name(lr)}", size, lr, f"LR sweep: {size} at lr {lr:g}, 20 tokens/param",
                            "A: learning-rate sweep"))
    return runs


def render(entry: dict) -> str:
    cfg = entry["config"]
    config_from_dict(cfg)  # fails loudly on a bad value
    n = estimate_param_counts(ModelConfig(**cfg["model"]))["total"]
    head = (
        f"# Generated by scripts/make_configs.py (edit the script, not this file).\n"
        f"# {entry['group']}. Model {entry['size']}: {n / 1e6:.1f}M parameters, "
        f"{cfg['train']['tokens'] / 1e6:.0f}M training tokens.\n"
    )
    return head + yaml.safe_dump(cfg, sort_keys=False, width=120)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="only check that the files are up to date")
    args = ap.parse_args(argv)
    wanted = {f"{e['config']['name']}.yaml": render(e) for e in all_runs()}
    if args.check:
        bad = [n for n, text in wanted.items() if not (OUT / n).exists() or (OUT / n).read_text() != text]
        extra = sorted(p.name for p in OUT.glob("*.yaml") if p.name not in wanted) if OUT.exists() else []
        for n in bad:
            print(f"out of date or missing: configs/exp/{n}")
        for n in extra:
            print(f"not made by this script: configs/exp/{n}")
        if bad or extra:
            print("run: python scripts/make_configs.py")
            return 1
        return 0
    OUT.mkdir(parents=True, exist_ok=True)
    for n, text in wanted.items():
        (OUT / n).write_text(text)
    print(f"wrote {len(wanted)} configs to {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
